### PR TITLE
Fix building errors

### PR DESCRIPTION
**Pull request by vycius**
After merging #11 building app was no longer working. App was missing few dimmensions, colors. Also there was some problems related to Action Bar and AppBar/Toolbar and AppTheme.

### CODE REVIEW

**Comment by ViliusKraujutis** [comment]
:+1:

**Comment by ViliusKraujutis** [comment]
Although could not see why tests were failing in Travis.

**Comment by tadaskay** [comment]
```
* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!
```

**Comment by tadaskay** [comment]
I guess it shouldn't test with connected device unless there's gradle config to launch a device, too. Task configuration needs a tweak.

**Comment by vycius** [comment]
Yeah. Forget to add dependency in `.travis.yml` for `android 23` device and launch it. I will make MR for that later. At least now project builds successfully. 
Also Travis build status icon has a typo in url. I will make another MR for that.

**Pull request merged**
