### PR TITLE
New home screen

### PR DESCRIPTION
**Pull request by vycius**
https://trello.com/c/ccWj59tM/43-rework-home-screen

screenshot_20160207-115932

@ViliusKraujutis @RenatBuga @narkusv @GediminasZukas

### CODE REVIEW

**Comment by RenatBuga** [comment]
Changed paddings between elements in _main_activity.xml_ as per prototype

`<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@color/content_background"
    android:orientation="vertical">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/colorPrimary"
        android:contentDescription="@string/app_name"
        android:scaleType="centerInside"
        android:src="@drawable/ic_logo_white" />


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:paddingLeft="12dp"
        android:paddingRight="12dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/home_report_problem"
                style="@style/HomeScreenButtonStyle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawableTop="@drawable/home_new_report"
                android:text="@string/home_report_a_problem" />

            <TextView
                android:id="@+id/home_my_problems"
                style="@style/HomeScreenButtonStyle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawableTop="@drawable/home_my_problems"
                android:text="@string/home_my_problems" />

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/home_list_of_problems"
                style="@style/HomeScreenButtonStyle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawableTop="@drawable/home_list_of_problems"
                android:text="@string/home_list_of_reports" />

            <TextView
                android:id="@+id/home_map_of_problems"
                style="@style/HomeScreenButtonStyle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawableTop="@drawable/home_map_of_problems"
                android:text="@string/home_map_of_problems" />
        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/home_my_profile"
                style="@style/HomeScreenButtonStyle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawableTop="@drawable/home_my_profile"
                android:text="@string/home_my_profile" />

            <TextView
                android:id="@+id/home_about"
                style="@style/HomeScreenButtonStyle"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:drawableTop="@drawable/home_about"
                android:text="@string/home_about" />
        </LinearLayout>
    </LinearLayout>
</LinearLayout>
```

</ScrollView>`

**Comment by RenatBuga** [comment]
Made changes in styles.xml

```
    <style name="HomeScreenButtonStyle" parent="AppTheme">
        <item name="android:typeface">sans</item>
        <item name="android:gravity">center_horizontal</item>
        <item name="android:layout_gravity">center_horizontal</item>
        <item name="android:paddingTop">32dp</item>
        <item name="android:drawablePadding">8dp</item>
        <item name="android:textColor">@color/home_button_text_color</item>
        <item name="android:textSize">16sp</item>
    </style>
```

@vycius

**Comment by RenatBuga** [comment]
@vycius : I suggest to replace the ImageView that simulates the app bar with a proper app bar. In this case when scrolling the content will go under the bar. Additionally, it will add shadow, as it is present on other screens.

**Comment by vycius** [comment]
@RenatBuga changed paddings and added toolbar.
About paddings 

``` xml
        <item name="android:paddingTop">32dp</item>
```

IMHO is too big. Applied `32 dp` from toolbar and `16 dp` between home screen buttons. Is it ok ? 
screenshot_20160207-184452

**Comment by RenatBuga** [comment]
@vycius : :+1:

**Comment by eronisko** [comment]
Can this be merged?

**Pull request merged**
