### PR TITLE
Refine my profile

### PR DESCRIPTION
**Pull request by vycius**
Task https://trello.com/c/SDL1ZIhq/52-make-my-contacts-screen

Haven't added Google+ login, because current implementation requires additional changes to get telephone number. 

screenshot_20160515-172609
@GediminasZukas @eronisko @RenatBuga @ViliusKraujutis @narkusv

### CODE REVIEW

**Comment by GediminasZukas** [comment]
Implemented feature seems to be :+1: 

But I am getting such crash: 

`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference                                                                        at lt.vilnius.tvarkau.views.adapters.ProblemsListAdapter$1.onClick(ProblemsListAdapter.java:84)`

when I try to press on problem row in ProblemsListFragment. The crash only occurs in rows with grey (placeholder?) problem images on the right side.

device-2016-05-19-144351

**Comment by vycius** [comment]
This crash is fixed by https://github.com/vilnius/tvarkau-vilniu/pull/42/files#diff-e073b43f5b409f6302f35eb03dc2e524L84

**Comment by vycius** [comment]
@RenatBuga paddings and background color will be changed in separate Pull Request.

**Comment by vycius** [comment]
Background and padding PR https://github.com/vilnius/tvarkau-vilniu/pull/45

**Comment by RenatBuga** [comment]
1. [Error in email field](https://cloud.githubusercontent.com/assets/15831041/15482155/086906c2-2126-11e6-9d07-2323a1e2b3ee.png) just after you start typing
2. [Error in phone field](https://cloud.githubusercontent.com/assets/15831041/15482201/3947f37a-2126-11e6-9e78-66758daf7d0b.png) just after you focus on it.
3. None of the fields [should be obligatory](https://cloud.githubusercontent.com/assets/15831041/15482089/c8c62676-2125-11e6-9473-1a99b1fd38b3.png). The Save function should go throught even if none of the fields are filled. This is valid especially for the case when you no longer want to share your personal information with the service.
4. Add a [dialog warning](https://cloud.githubusercontent.com/assets/15831041/15482077/b7da3492-2125-11e6-8cd0-a6d0ed4aee5f.png) of loosing data when hitting the back button before saving.

**Pull request merged**
