### PR TITLE
My profile enchantments

### PR DESCRIPTION
**Pull request by vycius**
screenshot_20160524-091846
- Autofill with Google sign in;
- Changed background
- Removed fields validation on the fly

Fixes for https://github.com/vilnius/tvarkau-vilniu/pull/44 https://github.com/vilnius/tvarkau-vilniu/pull/45
@RenatBuga Back button should show dialog if there any changes made. Haven't made any changes related to this.
@RenatBuga center vertical align in already applied see the screenshot. 
screenshot_20160524-092421
@GediminasZukas @eronisko @RenatBuga @ViliusKraujutis @narkusv

### CODE REVIEW

**Comment by GediminasZukas** [comment]
:+1: 
@RenatBuga what do you think?

**Comment by RenatBuga** [comment]
On screens looks OK. Is there a build to check this?

**Comment by vycius** [comment]
@RenatBuga as always .apk file is inside Bitrise https://www.bitrise.io/artifact/201499/p/327b0cd1d392ae521e7adf511184570d

**Comment by vycius** [comment]
Merging this. If some problems occurs we will fix them with separate PR.

**Comment by RenatBuga** [comment]
:+1:

**Pull request merged**
