### PR TITLE
Drop retrolambda

### PR DESCRIPTION
**Pull request by mjurkus**
Improved overall build speeds by leveraging gradle incremental and kotlin incremental builds.

Ensure that these properties are added to you `gradle.properties`

```
kotlin.incremental=true
org.gradle.daemon=true
```

Although these can be added directly to our project.

### CODE REVIEW

**Comment by vycius** [comment]
Have you done any benchmarks on speed gain ?

**Comment by vycius** [comment]
```
kotlin.incremental=true
org.gradle.daemon=true
```
What about adding these lines to projet `gradle.properties` ?

**Review by vycius — APPROVED** [review]

**Comment by mjurkus** [comment]
Some numbers:

Cold - Gradle daemon stopped
Warm - with code changes
```
w/ Retrolambda
Cold: 33s
No change 1: 5.2s
No change 2: 1.13s
Warm 1: 5.3s
Warm 2: 4.9s

w/o Retrolambda
Cold: 35s
No change 1: 1.2s
No change 2: 1.05s
Warm 1: 5.1s 
Warm 2: 5.02s
```

Performance increase is marginal, but as more KT code is added they will get only better.

**Comment by mjurkus** [comment]
There is still something that breaks incremental builds as from time to time even with unchanged code full compilation is performed.
Need to look into that later.

Most likely some code generating tool.

**Pull request merged**
