### PR TITLE
Add initial implementation of ProblemsListActivity

### PR DESCRIPTION
**Pull request by ViliusKraujutis**
Stuff done:
- Added Master/details activities for Problems (details should be improved)
- Integrated ButterKnife to reduce boilerplate code
- Add Dummy problems generator

Things left to do:
- Improve style 
- Image loading from cloud (now it's just stub thumb image)
- Tests
- Wiring to API

Try APK from [here](https://drive.google.com/file/d/0B8udh8s3XISyRkQ5T1ZVbFM2a0E/view?usp=sharing)

Now it looks like this:
image
image

relates to #9

### CODE REVIEW

**Comment by overengineered** [comment]
Looks good

**Comment by RenatBuga** [comment]
@ViliusKraujutis : for my curiosity, why you didn't use my XML layout?

**Comment by ViliusKraujutis** [comment]
@RenatBuga, if you mean [this XML](https://codeforvilnius.slack.com/archives/tvarkau-vilniu/p1447719089000187), which you've shared in chat, so it's just an image, not an XML.

**Comment by RenatBuga** [comment]
@ViliusKraujutis : I mean [this file](https://trello.com/c/aEoJeUMs/15-cut-design-to-xml-layouts)

**Comment by ViliusKraujutis** [comment]
I was not aware about it. Actually forgot to check there. But looked at that file - it's not reusable, because it's monolithical - not using a ListView. But still, would have been beneficial to take a look at font sizes, margin sizes, font colors etc. Will be good to take a look later to improve current list row's layout.

**Pull request merged**
